apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: policyholderdeploy
  name: policyholderdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policyholderdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: policyholderdeploy
    spec:
      containers:
      - image: eswaribala/siemensnov2025repo:policyholderapi
        name: policyholdersapp
        resources: {}          
        
        env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysql:3306/policyholderdb?useSSL=false
            #- name: OTEL_EXPORTER_JAEGER_ENDPOINT
              #value: "http://localhost:14250"
            #- name: OTEL_SERVICE_NAME
              #value: "patientapi"
            #- name: OTEL_TRACES_SAMPLER
              #value: "always_on"
      #imagePullSecrets:  
      #- name: globalaks-key

status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: policyholderservice
  name: policyholderservice
spec:
    
  ports:
  - protocol: TCP
    port: 7074
    targetPort: 7074
    name: http
  
  selector:
    app: policyholderdeploy
  type: LoadBalancer

