version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=vehicleproddb
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432


  vehicle-api:
    image: vehicleapi
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vehicleproddb
      - EUREKA__CLIENT__SERVICEURL=http://host.docker.internal:8761/eureka/

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
      - "7074-7076:7076"
        #- 7076:7076

    volumes:
      - /data/compose-app
    #networks:
      #- boanetwork


### put all the networks here
#networks:
  #boanetwork:
networks:
  default:
    external:
      name: siemensnetwork

  